* VSCODE Config

  This repo contains my settings for visual-studio-code.

** Installation

   Clone the repository in the location of User settings folder. If you have
   already made modifications to you VSCode settings you may have to delete this
   folder first.

   #+BEGIN_SRC shell
     git clone https://github.com/danilevy1212/vscode-config.git \
      ".config/Code/User"
   #+END_SRC

   The name of the "Code" folder may vary depending on the installed Visual Studio Code
   version. Lastly, to install all the extensions run the ~install-extensions.sh~
   script. From the User directory run:


   #+BEGIN_SRC shell
     ./install-extensions.sh
   #+END_SRC


    Optionally, you can enable a set of custom git-hooks to automate the process
    of extension management, by running:

    #+BEGIN_SRC shell
      git config core.hooksPath .githooks
    #+END_SRC

    or

    #+BEGIN_SRC shell
      find .git/hooks -type l -exec rm {} \;
      find .githooks -type f -exec ln -sf ../../{} .git/hooks/ \;
    #+END_SRC


*** Warning

    As of the time of writing, vs-code does not fully suport the [[https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html][XDG Base
    Directory Specification]], as the user cannot change the directory of the
    ~~/.vscode[- VERSION]/~ folder.

    There is a open [[https://github.com/microsoft/vscode/issues/84808][github issue]] where a solution to this problem is being discussed.
